package com.idhub.wallet.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.idhub.wallet.greendao.entity.AssetsModel;

import com.idhub.wallet.greendao.db.AssetsModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig assetsModelDaoConfig;

    private final AssetsModelDao assetsModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        assetsModelDaoConfig = daoConfigMap.get(AssetsModelDao.class).clone();
        assetsModelDaoConfig.initIdentityScope(type);

        assetsModelDao = new AssetsModelDao(assetsModelDaoConfig, this);

        registerDao(AssetsModel.class, assetsModelDao);
    }
    
    public void clear() {
        assetsModelDaoConfig.clearIdentityScope();
    }

    public AssetsModelDao getAssetsModelDao() {
        return assetsModelDao;
    }

}
