package com.idhub.wallet.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.idhub.wallet.greendao.entity.AssetsModel;
import com.idhub.wallet.me.information.entity.UploadIDHubInfoEntity;
import com.idhub.wallet.me.information.entity.UploadFileEntity;

import com.idhub.wallet.greendao.db.AssetsModelDao;
import com.idhub.wallet.greendao.db.UploadIDHubInfoEntityDao;
import com.idhub.wallet.greendao.db.UploadFileEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig assetsModelDaoConfig;
    private final DaoConfig uploadIDHubInfoEntityDaoConfig;
    private final DaoConfig uploadFileEntityDaoConfig;

    private final AssetsModelDao assetsModelDao;
    private final UploadIDHubInfoEntityDao uploadIDHubInfoEntityDao;
    private final UploadFileEntityDao uploadFileEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        assetsModelDaoConfig = daoConfigMap.get(AssetsModelDao.class).clone();
        assetsModelDaoConfig.initIdentityScope(type);

        uploadIDHubInfoEntityDaoConfig = daoConfigMap.get(UploadIDHubInfoEntityDao.class).clone();
        uploadIDHubInfoEntityDaoConfig.initIdentityScope(type);

        uploadFileEntityDaoConfig = daoConfigMap.get(UploadFileEntityDao.class).clone();
        uploadFileEntityDaoConfig.initIdentityScope(type);

        assetsModelDao = new AssetsModelDao(assetsModelDaoConfig, this);
        uploadIDHubInfoEntityDao = new UploadIDHubInfoEntityDao(uploadIDHubInfoEntityDaoConfig, this);
        uploadFileEntityDao = new UploadFileEntityDao(uploadFileEntityDaoConfig, this);

        registerDao(AssetsModel.class, assetsModelDao);
        registerDao(UploadIDHubInfoEntity.class, uploadIDHubInfoEntityDao);
        registerDao(UploadFileEntity.class, uploadFileEntityDao);
    }
    
    public void clear() {
        assetsModelDaoConfig.clearIdentityScope();
        uploadIDHubInfoEntityDaoConfig.clearIdentityScope();
        uploadFileEntityDaoConfig.clearIdentityScope();
    }

    public AssetsModelDao getAssetsModelDao() {
        return assetsModelDao;
    }

    public UploadIDHubInfoEntityDao getUploadIDHubInfoEntityDao() {
        return uploadIDHubInfoEntityDao;
    }

    public UploadFileEntityDao getUploadFileEntityDao() {
        return uploadFileEntityDao;
    }

}
