package com.idhub.wallet.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.idhub.wallet.greendao.entity.UploadIDHubInfoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "UPLOAD_IDHUB_INFO_ENTITY".
*/
public class UploadIDHubInfoEntityDao extends AbstractDao<UploadIDHubInfoEntity, Long> {

    public static final String TABLENAME = "UPLOAD_IDHUB_INFO_ENTITY";

    /**
     * Properties of entity UploadIDHubInfoEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FirstName = new Property(1, String.class, "firstName", false, "FIRST_NAME");
        public final static Property LastName = new Property(2, String.class, "lastName", false, "LAST_NAME");
        public final static Property Birthday = new Property(3, String.class, "birthday", false, "BIRTHDAY");
        public final static Property Country = new Property(4, String.class, "country", false, "COUNTRY");
        public final static Property ResidenceCountry = new Property(5, String.class, "residenceCountry", false, "RESIDENCE_COUNTRY");
        public final static Property IdcardNumber = new Property(6, String.class, "idcardNumber", false, "IDCARD_NUMBER");
        public final static Property PassportNumber = new Property(7, String.class, "passportNumber", false, "PASSPORT_NUMBER");
        public final static Property TaxNumber = new Property(8, String.class, "taxNumber", false, "TAX_NUMBER");
        public final static Property SsnNumber = new Property(9, String.class, "ssnNumber", false, "SSN_NUMBER");
        public final static Property Address = new Property(10, String.class, "address", false, "ADDRESS");
        public final static Property Phone = new Property(11, String.class, "phone", false, "PHONE");
        public final static Property PhoneDialingCode = new Property(12, String.class, "phoneDialingCode", false, "PHONE_DIALING_CODE");
        public final static Property Email = new Property(13, String.class, "email", false, "EMAIL");
        public final static Property ResidenceCountryIsoCode = new Property(14, String.class, "residenceCountryIsoCode", false, "RESIDENCE_COUNTRY_ISO_CODE");
        public final static Property CountryIsoCode = new Property(15, String.class, "countryIsoCode", false, "COUNTRY_ISO_CODE");
    }


    public UploadIDHubInfoEntityDao(DaoConfig config) {
        super(config);
    }
    
    public UploadIDHubInfoEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"UPLOAD_IDHUB_INFO_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FIRST_NAME\" TEXT," + // 1: firstName
                "\"LAST_NAME\" TEXT," + // 2: lastName
                "\"BIRTHDAY\" TEXT," + // 3: birthday
                "\"COUNTRY\" TEXT," + // 4: country
                "\"RESIDENCE_COUNTRY\" TEXT," + // 5: residenceCountry
                "\"IDCARD_NUMBER\" TEXT," + // 6: idcardNumber
                "\"PASSPORT_NUMBER\" TEXT," + // 7: passportNumber
                "\"TAX_NUMBER\" TEXT," + // 8: taxNumber
                "\"SSN_NUMBER\" TEXT," + // 9: ssnNumber
                "\"ADDRESS\" TEXT," + // 10: address
                "\"PHONE\" TEXT," + // 11: phone
                "\"PHONE_DIALING_CODE\" TEXT," + // 12: phoneDialingCode
                "\"EMAIL\" TEXT," + // 13: email
                "\"RESIDENCE_COUNTRY_ISO_CODE\" TEXT," + // 14: residenceCountryIsoCode
                "\"COUNTRY_ISO_CODE\" TEXT);"); // 15: countryIsoCode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"UPLOAD_IDHUB_INFO_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UploadIDHubInfoEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String firstName = entity.getFirstName();
        if (firstName != null) {
            stmt.bindString(2, firstName);
        }
 
        String lastName = entity.getLastName();
        if (lastName != null) {
            stmt.bindString(3, lastName);
        }
 
        String birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindString(4, birthday);
        }
 
        String country = entity.getCountry();
        if (country != null) {
            stmt.bindString(5, country);
        }
 
        String residenceCountry = entity.getResidenceCountry();
        if (residenceCountry != null) {
            stmt.bindString(6, residenceCountry);
        }
 
        String idcardNumber = entity.getIdcardNumber();
        if (idcardNumber != null) {
            stmt.bindString(7, idcardNumber);
        }
 
        String passportNumber = entity.getPassportNumber();
        if (passportNumber != null) {
            stmt.bindString(8, passportNumber);
        }
 
        String taxNumber = entity.getTaxNumber();
        if (taxNumber != null) {
            stmt.bindString(9, taxNumber);
        }
 
        String ssnNumber = entity.getSsnNumber();
        if (ssnNumber != null) {
            stmt.bindString(10, ssnNumber);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(11, address);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(12, phone);
        }
 
        String phoneDialingCode = entity.getPhoneDialingCode();
        if (phoneDialingCode != null) {
            stmt.bindString(13, phoneDialingCode);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(14, email);
        }
 
        String residenceCountryIsoCode = entity.getResidenceCountryIsoCode();
        if (residenceCountryIsoCode != null) {
            stmt.bindString(15, residenceCountryIsoCode);
        }
 
        String countryIsoCode = entity.getCountryIsoCode();
        if (countryIsoCode != null) {
            stmt.bindString(16, countryIsoCode);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UploadIDHubInfoEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String firstName = entity.getFirstName();
        if (firstName != null) {
            stmt.bindString(2, firstName);
        }
 
        String lastName = entity.getLastName();
        if (lastName != null) {
            stmt.bindString(3, lastName);
        }
 
        String birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindString(4, birthday);
        }
 
        String country = entity.getCountry();
        if (country != null) {
            stmt.bindString(5, country);
        }
 
        String residenceCountry = entity.getResidenceCountry();
        if (residenceCountry != null) {
            stmt.bindString(6, residenceCountry);
        }
 
        String idcardNumber = entity.getIdcardNumber();
        if (idcardNumber != null) {
            stmt.bindString(7, idcardNumber);
        }
 
        String passportNumber = entity.getPassportNumber();
        if (passportNumber != null) {
            stmt.bindString(8, passportNumber);
        }
 
        String taxNumber = entity.getTaxNumber();
        if (taxNumber != null) {
            stmt.bindString(9, taxNumber);
        }
 
        String ssnNumber = entity.getSsnNumber();
        if (ssnNumber != null) {
            stmt.bindString(10, ssnNumber);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(11, address);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(12, phone);
        }
 
        String phoneDialingCode = entity.getPhoneDialingCode();
        if (phoneDialingCode != null) {
            stmt.bindString(13, phoneDialingCode);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(14, email);
        }
 
        String residenceCountryIsoCode = entity.getResidenceCountryIsoCode();
        if (residenceCountryIsoCode != null) {
            stmt.bindString(15, residenceCountryIsoCode);
        }
 
        String countryIsoCode = entity.getCountryIsoCode();
        if (countryIsoCode != null) {
            stmt.bindString(16, countryIsoCode);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UploadIDHubInfoEntity readEntity(Cursor cursor, int offset) {
        UploadIDHubInfoEntity entity = new UploadIDHubInfoEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // firstName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // lastName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // birthday
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // country
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // residenceCountry
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // idcardNumber
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // passportNumber
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // taxNumber
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // ssnNumber
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // address
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // phone
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // phoneDialingCode
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // email
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // residenceCountryIsoCode
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15) // countryIsoCode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UploadIDHubInfoEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFirstName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLastName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBirthday(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCountry(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setResidenceCountry(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIdcardNumber(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPassportNumber(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setTaxNumber(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSsnNumber(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setAddress(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setPhone(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setPhoneDialingCode(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setEmail(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setResidenceCountryIsoCode(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setCountryIsoCode(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UploadIDHubInfoEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UploadIDHubInfoEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UploadIDHubInfoEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
